#!/bin/bash
#===============================================================================
#
#          FILE: 04_jellyfishh
# 
#         USAGE: ./04_jellyfish $input
# 
#   DESCRIPTION: nano script to run jellyfish and genome scope  
# 
#       OPTIONS: only standard options are used here
#  REQUIREMENTS: HiFI or nano-hq or illumina only
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Q. Rougemont 
#  ORGANIZATION: 
#       CREATED: 07/08/2024 11:54:40
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

#===============================================================================
#       External variable 
input=$1        #fastq.gz file read (HiFi on nano-hq)
ploidy=$2       #an integer : either 1 or 2
kmer_length=$3  #generally use the size of 21
LENGTH=$4       #genome size in bp 
datatype=$5     #hifi or ONT
#===============================================================================
source .cpu_mem

# - jellyfish 
outdir=04_jellyfish
mkdir $outdir 2>/dev/null

if [ ! -s "$outdir"/reads.histo ] 
then
   #run jellyfish 
    jellyfish count -C -m 21 -s 1000000000 -t "$NCPUS_JELLY" <(zcat "$input") -o "$outdir"/reads.jf

    if ! jellyfish histo -t "$NCPUS_JELLY" "$outdir"/reads.jf > "$outdir"/reads.histo ; then 
	    echo "jellyfish failed"
	    exit 1
    fi
fi
#===============================================================================

# - genomescope2:
if [ ! -s "$outdir"/linear_plot.png ] 
then
    if ! genomescope2 -i "$outdir"/reads.histo  -k "$kmer_length" -p "$ploidy" -o "$outdir" ; 
    then
    	echo "genomescope failed"
    	exit 1
    fi
else
    echo "genomescope2 output already exist"
fi

 #verify also the read error rate estimated from genomescope2:
 err=$( tail -n1 "$outdir"/summary.txt |awk '{print $4/100}' ) 

if [ $datatype == 'hifi' ] ;then threshold_err=0.01 ; else threshold_err=0.02 ; fi
#check quality:
 if awk -v d="$err" -v t="$threshold_err" 'BEGIN{exit !(d > t)}' ; 
 then 
     echo "=================================================================="
     echo "!!!warning genome scope estimate of sequencing error is bad" ; 
     echo "please verify genomeScope profiles and summary.txt !!!!" 
     echo "=================================================================="
     exit 
 else 
     echo " " ; 
 fi

